### ISSUE TITLE
Create capture endpoint of order management api has wrong path

### ISSUE THREAD

**Issue by lommer-pns24** [klarna/kco_rest_php#50] opened 2020-02-07 15:16 UTC
The path to the create capture endpoint of order management api lacks the required leading 'ordermanagement/v1/orders/'
Good:
![get_order_request_data](https://user-images.githubusercontent.com/42031300/74040885-e43f6900-49c4-11ea-9b36-5da83602d019.PNG)
Bad:
![capture_request_data](https://user-images.githubusercontent.com/42031300/74040913-f4574880-49c4-11ea-8502-16cd59474b6c.PNG)

.

**Comment by alexions** [comment] 2020-02-10 09:42
HI @lommer-pns24 

Unfortunately, I cannot reproduce the issue. I checked the [Create Capture example](https://github.com/klarna/kco_rest_php/blob/v4.x/docs/examples/OrderManagementAPI/Orders/create_capture.php) and it works well.

Could you provide more details and steps how to reproduce this issue?

Thanks

**Comment by lommer-pns24** [comment] 2020-02-10 09:58
Hi @alexions 
Aha, so it seems to work with Order::createCapture. However, I expected that Capture::create should be used instead. The error occurs using Capture::create.
However, I found I can just pass the proper url to the capture client constructor as a workaround. Still it seems to be intended that the url is set correctly automatically as done in the order client. 
Best

**Comment by alexions** [comment] 2020-02-10 10:27
Thanks for the clarification! Yeah, there are two ways how to work with Captures and the easies - through the OrderManagement\Orders. 

Although you still can use the Capture class to create a new capture, but you need to provide the parent Order URL manually.

I will close the issue. Feel free to reopen it if you find any other problems.
Thanks!

**Closed as completed by alexions** 2020-02-10 10:27 UTC
