### ISSUE TITLE
PHP7 support?

### ISSUE THREAD

**Issue by eirikhm** [klarna/kco_rest_php#7] opened 2016-11-25 08:29 UTC
https://developers.klarna.com/en/gb/kco-v3/download/php claims that PHP 7 is currently not supported, but all tests seems to pass.

What are the issues with PHP7? We are about to upgrade our servers to PHP7, so we need to have a clear plan for this.

**Comment by AndriusBartulis** [comment] 2017-04-25 09:36
@eirikhm did you eventually move to PHP7? Did the SDK still work? Any issues?

**Comment by eirikhm** [comment] 2017-04-25 10:41
Short answer: Yeah, seems to work well. We had some custom code which caused some issues, but that's being resolved. I encourage heavy testing ;-)

**Comment by tommiehansen** [comment] 2017-05-16 09:56
I don't understand why PHP 5.x would work and PHP 7.x would not. What special depracated functions would be the cause to write that PHP 7.x is unsupported?

Also note that most depracated methods in PHP 5.6+ (released aug 2014...) also was depracated in 5.5+ meaning that it would be insane to use any of these in something released within the last 3 years basically. This in turn mean that PHP 7.x should work fine if the Klarna devs isn't insane. :)

**Comment by bubach** [comment] 2017-08-04 18:43
Started working on implementing this with PHP7 and so far no issues, except that the low Guzzle version requirement put me in dependency hell. (kludge fork with seemingly working Guzzle v6 support at https://github.com/Ridestore/kco_rest_php/) 

I actually prefered the older SDK's custom (and thin) cURL wrappers. At least when you're not updating stuff for > 2 years.

**Comment by mitemitreski** [comment] 2018-01-11 09:03
@bubach @tommiehansen  @eirikhm @AndriusBartulis this is fixed in v3

**Closed as completed by mitemitreski** 2018-01-11 09:03 UTC
